# Generated by Django 3.2.5 on 2021-09-01 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('first_name', models.CharField(max_length=15, null=True)),
                ('last_name', models.CharField(max_length=12, null=True)),
                ('age', models.PositiveSmallIntegerField(null=True)),
                ('course_Name', models.CharField(max_length=15, null=True)),
                ('email', models.EmailField(max_length=17, null=True)),
                ('contract', models.FileField(null=True, upload_to='')),
                ('cource', models.CharField(max_length=12, null=True)),
                ('phone_number', models.CharField(max_length=15, null=True)),
                ('trainer_Bio', models.TextField(null=True)),
                ('id', models.CharField(max_length=18, primary_key=True, serialize=False)),
                ('profile', models.FileField(null=True, upload_to='images/')),
                ('gendar', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Others')], max_length=19, null=True)),
                ('nationality', models.CharField(choices=[('K', 'Kenya'), ('U', 'Uganda'), ('R', 'Rwanda')], max_length=23, null=True)),
                ('language', models.CharField(choices=[('E', 'English'), ('k', 'ukiswahili'), ('ki', 'ukinywaranda')], max_length=6, null=True)),
            ],
        ),
    ]
