# Generated by Django 3.2.5 on 2021-09-25 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='language',
            field=models.CharField(choices=[('E', 'uEnglish'), ('k', 'ukiswahili'), ('ki', 'ukinywaranda')], max_length=6, null=True),
        ),
    ]
