# Generated by Django 3.2.5 on 2021-08-25 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_rename_course_name_courses_course_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='course_Name',
        ),
        migrations.AddField(
            model_name='courses',
            name='course_name',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
