# Generated by Django 3.2.5 on 2021-08-25 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20210825_0535'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='trainer_profile',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='courses',
            name='course_code',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='courses',
            name='course_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='courses',
            name='coursedescription',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='courses',
            name='trainer',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
