# Generated by Django 3.2.5 on 2021-09-09 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20210825_1225'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courses',
            old_name='trainer_profile',
            new_name='profile',
        ),
    ]
