# Generated by Django 3.2.5 on 2021-09-01 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=15, null=True)),
                ('last_name', models.CharField(max_length=12, null=True)),
                ('age', models.PositiveSmallIntegerField(null=True)),
                ('date_of_birth', models.DateField(null=True)),
                ('rolenumber', models.CharField(max_length=17, null=True)),
                ('district', models.CharField(max_length=18, null=True)),
                ('gender', models.CharField(choices=[('1', 'Male'), ('2', 'Female'), ('3', 'Others')], max_length=19, null=True)),
                ('email', models.EmailField(max_length=30, null=True)),
                ('student_id', models.PositiveSmallIntegerField(null=True)),
                ('nationality', models.CharField(choices=[('1', 'Kenya'), ('2', 'Uganda'), ('3', 'Rwanda')], max_length=23, null=True)),
                ('nationality_id', models.CharField(max_length=20, null=True)),
                ('medical_report', models.FileField(null=True, upload_to='')),
                ('laptopserialnumber', models.CharField(max_length=16, null=True)),
                ('date_of_enrollment', models.DateField(null=True)),
                ('profile', models.ImageField(null=True, upload_to='images/')),
                ('phone_number', models.CharField(max_length=15, null=True)),
                ('language', models.CharField(choices=[('1', 'English'), ('2', 'kiswahili'), ('3', 'kinyaradwa')], max_length=6, null=True)),
            ],
        ),
    ]
